index:
    path: /
    controller: App\Controller\SiteController::index

#api_login_check:
#    path: /api/login_check

post:
    path: /api/posts/{postId}
    controller: App\Controller\API\PostController::getPost

posts:
    path: /api/posts
    controller: App\Controller\API\PostController::getPosts

postComment:
    path: /api/postComment
    controller: App\Controller\API\PostController::postComment