index:
    path: /
    controller: App\Controller\SiteController::index

#api_login_check:
#    path: /api/login_check

post:
    path: /api/posts/{postId}
    controller: App\Controller\API\PostController::getPost